<?php
// Do not edit this file. Generated by admin script.
// simplemembershiplibrary Configuration file
$user_configuration['release']['version']='4.1.2 Free';
$user_configuration['release']['date']='24.07.2017';
$user_configuration['acl_group_set']='18,23';
$user_configuration['acl_group_set_email']='0';
$user_configuration['useradd_notification_email']='buchastiy1989-facilitator@gmail.com';
$user_configuration['senders_email']='Ordasvit';
$user_configuration['allow_fieldsets']='profile';$user_configuration['preregister']='';
$user_configuration['activationmsg']='<p>Congratulations your account has been activated!</p>';
$user_configuration['admin_created_msg']='<p>Administrator notification message on account creation</p>';
$user_configuration['user_created_msg']='<p>Congratulations your account has been successfully created!</p>';
$user_configuration['user_enabled_msg']='<p>Congratulations your account has been enabled by administrator!</p>';
$user_configuration['user_approve_msg']='<p>Congratulations your account has been approved by administrator!</p>';
$user_configuration['user_disapprove_msg']='<p>Your account has been disapproved!</p>';
$user_configuration['default_group']='2';
$user_configuration['other_profiles']='-2';
$user_configuration['before_end_notify'] = '0';
$user_configuration['before_end_notify_days'] = '2';
$user_configuration['before_end_notify_email'] = '';
$user_configuration['admin_created_msg_for_user'] = '<p>User membership expire: {username}({user_email})ID: {id}soon expire</p>';
$user_configuration['admin_created_msg_for_admin']= '<p>User membership expire: {username}({user_email}) ID: {id} soon expire</p>';

?>
